/*
 Copyright Lolo_32 2015, All right reserved
*/
var myChat=myChat||{};
(function(k,h,c){function f(f,a){var b=k.createElement(f);a.b&&(b.id=a.b);a.a&&(b.className=a.a);a.l&&(b.maxLength=a.l);a.c&&(b.type=a.c);a.i&&(b.value=a.i);a.j&&(b.autocomplete=a.j);a.f&&(b.innerHTML=a.f);return b}function v(){function c(a,f){return a.replace(f?/(?:<|\\x3c)[\w:\/\s="'\\\-]+?(?:>|\\x3e)/gi:/(?:<|\\x3c)(?:\/?[ac-hj-z][\w:\/\s="'\\\.\-]+?|\/?[bi][\w:\/\s="'\\\.\-]+?)(?:>|\\x3e)/gi,"")}function u(l,p,b){var g,d,e;g=f("li",{a:"chatMessageLine"});l=new Date(l);e=new Date;e.setUTCDate(l.getUTCDate());
e.setUTCFullYear(l.getUTCFullYear());e.setUTCHours(l.getUTCHours());e.setUTCMinutes(l.getUTCMinutes());e.setUTCMonth(l.getUTCMonth());e.setUTCSeconds(l.getUTCSeconds());l=f("span",{a:"chatDate",f:e.toLocaleString(h.language?h.language:h.browserLanguage?h.browserLanguage:h.systemLanguage?h.systemLanguage:h.userLanguage?h.userLanguage:a.locale,{hour:"2-digit",minute:"2-digit"}).replace(RegExp(" ","g"),"&nbsp;")});p=f("span",{a:"chatAuthor",f:c(p,!0)});b=c(b,!1);e=a.g;var n;for(d in e)e.hasOwnProperty(d)&&
(n=d.replace(".","\\.").replace("\\","\\\\").replace("*","\\*").replace("+","\\+").replace("(","\\(").replace(")","\\)").replace("[","\\[").replace("]","\\]").replace("{","\\{").replace("}","\\}"),n=new RegExp(n,"g"),b=b.replace(n,'<img src="'+e[d].url+'" alt="'+d+'"'+(e[d].w?' width="'+e[d].w+'"':"")+(e[d].h?' height="'+e[d].h+'"':"")+" />"));d=f("span",{a:"chatMessage",f:b});g.appendChild(l);g.appendChild(p);g.appendChild(d);return g}function b(){function f(a){e.insertBefore(u(a.date,a.name,a.msg),
e.firstElementChild)}var b=io(a.url),c=k.getElementById("chatForm"),g=k.getElementsByClassName("chatMsg")[0],d=k.getElementsByClassName("chatName")[0],e=k.getElementById("chatMessages");b.emit("join",a.m);b.on("reconnect",function(){b.emit("join",a.m)});c.addEventListener("submit",function(a){var e=g.value,m=d.value,r;a.preventDefault();1<e.length&&1<m.length&&(g.value="",e=e.substring(0,250),m=m.substring(0,30),a={msg:e,name:m},r=new Date,b.emit("message",a),f({date:r.valueOf(),name:m,msg:e}))});
b.on("message",function(a){f(a)});b.on("history",function(a){for(var b=a.length,d;e.hasChildNodes();)e.removeChild(e.childNodes[0]);for(d=0;d<b;++d)f(a[d])})}function t(){"undefined"===typeof io?setTimeout(t,100):setTimeout(b,100)}(function(){var a=f("script",{});a.async=!0;a.src="https://cdn.socket.io/socket.io-1.3.5.js";k.getElementsByTagName("head")[0].appendChild(a)})();(function(){var b,c,h,g,d,e;b=f("ul",{b:"chatMessages"});c=f("form",{b:"chatForm"});h=f("input",{a:"chatName",l:30,j:"on",c:"text"});
d=f("input",{b:"smileysButton",c:"button",i:"Smileys"});d.onclick=function(){function e(a,b){var c=f("div",{a:"smileyDiv"}),d=f("img",{}),g=f("br",{});d.src=b.url;b.h&&(d.height=parseInt(b.h,10));b.w&&(d.width=parseInt(b.w,10));d.alt=a;c.appendChild(d);c.appendChild(g);c.appendChild(k.createTextNode(a));return c}var b,d,c,g=window.open("","Smileys","resizable=yes,scrollbars=yes,width=250,height=300"),h;if(g){h=g.document;if(!h.head.hasChildNodes()){c=f("meta",{});c.setAttribute("charset","UTF-8");
h.head.appendChild(c);c=f("title",{});c.appendChild(k.createTextNode("Smileys"));h.head.appendChild(c);c=f("style",{});c.appendChild(k.createTextNode(a.o||".smileyDiv{text-align:center;padding:5px;margin:5px;float:left;border:dotted 1px;cursor:pointer;}"));h.head.appendChild(c);c=f("div",{b:"divGeneral"});for(b in a.g)a.g.hasOwnProperty(b)&&(d=a.g[b],d=e(b,d),d.onclick=function(){var a=b;return function(){var b=k.getElementsByClassName("chatMsg")[0],c=b.selectionStart,d=b.scrollLeft;b.value=b.value.slice(0,
c)+a+b.value.slice(b.selectionEnd);b.selectionStart=c+a.length;b.selectionEnd=c+a.length;b.scrollLeft=d;b.focus();g.close()}}(),c.appendChild(d));h.body.appendChild(c)}g.focus&&g.focus()}};e=f("input",{a:"chatSend",c:"submit",i:a.u});g=f("div",{b:"chatSend"});g.appendChild(e);e=f("div",{b:"divRight"});e.appendChild(g);g=f("div",{b:"chatName"});g.appendChild(h);g.appendChild(d);g.appendChild(e);h=f("input",{a:"chatMsg",l:250,j:"off",c:"text"});d=f("div",{b:"chatMsg"});d.appendChild(h);c.appendChild(g);
c.appendChild(d);q.appendChild(b);q.appendChild(c)})();t()}function w(){var a,c={},b="36candles anger anger2 baby baseballbat bear bearlove bearslove blah bravo bye byebye cabug coaxing coffee computfight computstop coupdetete cry denounces drool embrace fight giftlove happylove hehe hellokitty hit hug hurray iloveyou inlove inlove2 inlove3 letaime jetm juggling kiss lol! lol lovebanana lover mdr! mdr meal mercenary no not ofcourse rainlove rose teddybear thankyou toast unhappy whiteflag wine wineparty wink".split(" ");
for(a=0;a<b.length;++a)c[":"+b[a]+":"]={url:"http://croisic.baysse.fr/smileys/"+b[a]+".gif"};return c}var a={},q;a.url=c.url;a.s=c.div||"chatDiv";a.locale=c.locale||"fr-FR";a.m=c.session||k.baseURI;a.u=c.sendText||"Send";a.g=c.smileys||w();a.v=c.smileyHeight;a.A=c.smileyWidth;a.o=c.cssSmiley;a.url&&(q=k.getElementById(a.s))&&v()})(document,navigator,myChat);